### ISSUE TITLE
Announcement for Keynote Speakers

### ISSUE THREAD

**Issue by bkamapantula** [pythonindia/inpycon2023-tasks#59]
Hello,

I wanted to ideate on how we would like to announce the keynote speakers. I can think of two options:

1) One a week, spaced out across several weeks.
  - We can display on the website but announce on SM channels one-by-one.
2) Everyone at once.
  - This may delay the announcement until all the speakers are confirmed.

Any other possibilities? Thanks.

**Comment by bpkapkar** [comment]
1.  Keynote Speaker 1 -  Jessica Greene - https://drive.google.com/file/d/1EssHoiimSkmtei1iYCRl4n3M_OZxxWup/view?usp=drive_link
Bio - Jessica Greene is a self-taught slash community-taught Software Engineer, with a diverse background that includes film, television, and specialty coffee roasting. In 2017, she made the pivotal decision to retrain and add programming to her skill set, leading her to join the team at Ecosia in 2018. In her role, she leverages her Python and Golang skills to build and operate APIs, perform data analysis, and develop features that inspire users to make more climate-focused choices, thereby contributing to Ecosia's mission of global tree planting and a better planet.
Passionate about fostering diversity and inclusivity in tech, Jessica has been co-organizing PyLadies Berlin since 2018. She orchestrates events, workshops, and talks, and provides mentorship to other programmers. Recently, she joined the Python Software Foundation's Code of Conduct Work Group to further support the global community.
When she's not coding or at community events, Jessica enjoys reading, building Lego kits, knitting, dog-sitting, and exploring new aspects of software engineering.

2. Keynote Speaker 2  -  Marcelo Trylesinski - https://drive.google.com/file/d/1JgtgqiwIJU7pKnd3Kdq2tJ4iycc5VVRd/view?
Bio -  Marcelo is an open-source developer who has made significant contributions to the FastAPI community. He maintains Starlette, a critical dependency of FastAPI, and Uvicorn, a high-performance web server that powers FastAPI applications. His invaluable contributions led to his hiring as a senior software engineer by Pydantic, a widely used library for data validation and serialization. Apart from software development, Marcelo enjoys fitness, soccer, dancing, and photography. He's a well-rounded individual who's always eager to learn and grow.

3. Keynote Speaker 3 -  Ruhabh Mehtha  https://drive.google.com/file/d/1hOwF28CNW_h8bJIiOs58WJpgQl4sV1mc/view?usp=drive_link  Bio: https://www.linkedin.com/in/rushabhmehta1/

4. Keynote Speaker 4 - Cheuk Ting Ho  -https://drive.google.com/open?id=1Pi3CPZehh4APA1QvhkJalekzStoXP3df - 

Bio After having a career as a Data Scientist and Developer Advocate, Cheuk dedicated her work into the open-source community. She has co-founded Humble Data, a beginner Python workshop that has been happening around the world. Cheuk also contributes to multiple Open Source libraries like Hypothesis, Pytest, Pandas, Jupyter Notebook and Django. She has served the EuroPython Society board for two years and is now a fellow and director of the Python Software Foundation.
 
5.  Key Note Speaker  5  Shailesh Kumar  https://drive.google.com/file/d/1waIQDXZjf3Px-9Ya8E5Am_CbEbCgppQC/view?usp=sharing
Bio - Chief Data Scientist, CoE AI/ML Jio  

LinkedIn : https://www.linkedin.com/in/shaileshk/

SM Handles- https://twitter.com/cheukting_ho
https://www.linkedin.com/in/cheukting-ho
(for others, check my website https://cheuk.dev)
 
6. Keynote Speaker 4 - Master Link - https://drive.google.com/drive/folders/1m1mQywDdcGl7Zgze9C1tIiDpzHhphM4oP2YDuId6sKCXKcFdjXSzW3dpSfXoLq_2c4uDRHiQ?usp=sharing

@bkamapantula  : Do we have3rd and 4th  speaker bio that we have received that we need to take as reference in flyer

**Comment by RajatRajdeep** [comment]
Shailesh Kumar's Bio is missing. Please add it here so same can be added in the website.
@bpkapkar @bkamapantula

**Comment by bkamapantula** [comment]
@RajatRajdeep Updated here, please see: https://docs.google.com/spreadsheets/d/1KjMxjFRYZ8FQcHvbwWpwNZLxLhIJqw-BwKpmsHw4cjU/edit#gid=1218993700

I picked the information from https://www.jioinstitute.edu.in/faculty/dr-shailesh-kumar and his LinkedIn.

**Comment by RajatRajdeep** [comment]
Thanks a lot, @bkamapantula!

**Comment by inovizz** [comment]
This is done. hence closing it.
